// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
use uuid::Uuid;
#[derive(Queryable, Debug)]
pub struct Note {
    pub id: Uuid,
    pub owner: Uuid,
    pub label: String,
    pub content: String,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: Uuid,
    pub name: String,
    pub login: String,
    pub password: String,
}

